# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import environment_pb2 as protos_dot_environment__pb2


class RemoteEnvironmentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialization = channel.unary_unary(
                '/tensorflow.muprover.RemoteEnvironment/Initialization',
                request_serializer=protos_dot_environment__pb2.InitializationRequest.SerializeToString,
                response_deserializer=protos_dot_environment__pb2.InitializationResponse.FromString,
                )
        self.Finalization = channel.unary_unary(
                '/tensorflow.muprover.RemoteEnvironment/Finalization',
                request_serializer=protos_dot_environment__pb2.FinalizationRequest.SerializeToString,
                response_deserializer=protos_dot_environment__pb2.FinalizationResponse.FromString,
                )
        self.Step = channel.unary_unary(
                '/tensorflow.muprover.RemoteEnvironment/Step',
                request_serializer=protos_dot_environment__pb2.StepRequest.SerializeToString,
                response_deserializer=protos_dot_environment__pb2.StepResponse.FromString,
                )
        self.Reset = channel.unary_unary(
                '/tensorflow.muprover.RemoteEnvironment/Reset',
                request_serializer=protos_dot_environment__pb2.ResetRequest.SerializeToString,
                response_deserializer=protos_dot_environment__pb2.ResetResponse.FromString,
                )


class RemoteEnvironmentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Initialization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finalization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteEnvironmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialization': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialization,
                    request_deserializer=protos_dot_environment__pb2.InitializationRequest.FromString,
                    response_serializer=protos_dot_environment__pb2.InitializationResponse.SerializeToString,
            ),
            'Finalization': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalization,
                    request_deserializer=protos_dot_environment__pb2.FinalizationRequest.FromString,
                    response_serializer=protos_dot_environment__pb2.FinalizationResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=protos_dot_environment__pb2.StepRequest.FromString,
                    response_serializer=protos_dot_environment__pb2.StepResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=protos_dot_environment__pb2.ResetRequest.FromString,
                    response_serializer=protos_dot_environment__pb2.ResetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tensorflow.muprover.RemoteEnvironment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteEnvironment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Initialization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.muprover.RemoteEnvironment/Initialization',
            protos_dot_environment__pb2.InitializationRequest.SerializeToString,
            protos_dot_environment__pb2.InitializationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Finalization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.muprover.RemoteEnvironment/Finalization',
            protos_dot_environment__pb2.FinalizationRequest.SerializeToString,
            protos_dot_environment__pb2.FinalizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.muprover.RemoteEnvironment/Step',
            protos_dot_environment__pb2.StepRequest.SerializeToString,
            protos_dot_environment__pb2.StepResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.muprover.RemoteEnvironment/Reset',
            protos_dot_environment__pb2.ResetRequest.SerializeToString,
            protos_dot_environment__pb2.ResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
