# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import environment_pb2 as protos_dot_environment__pb2


class RemoteEnvironmentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Initialization = channel.unary_unary(
        '/tensorflow.muzero.RemoteEnvironment/Initialization',
        request_serializer=protos_dot_environment__pb2.InitializationRequest.SerializeToString,
        response_deserializer=protos_dot_environment__pb2.InitializationResponse.FromString,
        )
    self.Step = channel.unary_unary(
        '/tensorflow.muzero.RemoteEnvironment/Step',
        request_serializer=protos_dot_environment__pb2.ActionRequest.SerializeToString,
        response_deserializer=protos_dot_environment__pb2.ActionResponse.FromString,
        )


class RemoteEnvironmentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Initialization(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Step(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RemoteEnvironmentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Initialization': grpc.unary_unary_rpc_method_handler(
          servicer.Initialization,
          request_deserializer=protos_dot_environment__pb2.InitializationRequest.FromString,
          response_serializer=protos_dot_environment__pb2.InitializationResponse.SerializeToString,
      ),
      'Step': grpc.unary_unary_rpc_method_handler(
          servicer.Step,
          request_deserializer=protos_dot_environment__pb2.ActionRequest.FromString,
          response_serializer=protos_dot_environment__pb2.ActionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tensorflow.muzero.RemoteEnvironment', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
