# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import replay_buffer_pb2 as protos_dot_replay__buffer__pb2


class ReplayBufferStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Stats = channel.unary_unary(
        '/tensorflow.ReplayBuffer/Stats',
        request_serializer=protos_dot_replay__buffer__pb2.Empty.SerializeToString,
        response_deserializer=protos_dot_replay__buffer__pb2.StatsResponse.FromString,
        )
    self.SaveGame = channel.unary_unary(
        '/tensorflow.ReplayBuffer/SaveGame',
        request_serializer=protos_dot_replay__buffer__pb2.GameHistory.SerializeToString,
        response_deserializer=protos_dot_replay__buffer__pb2.SaveGameResponse.FromString,
        )
    self.SampleBatch = channel.unary_unary(
        '/tensorflow.ReplayBuffer/SampleBatch',
        request_serializer=protos_dot_replay__buffer__pb2.MiniBatchRequest.SerializeToString,
        response_deserializer=protos_dot_replay__buffer__pb2.MiniBatchResponse.FromString,
        )


class ReplayBufferServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Stats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveGame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SampleBatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReplayBufferServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Stats': grpc.unary_unary_rpc_method_handler(
          servicer.Stats,
          request_deserializer=protos_dot_replay__buffer__pb2.Empty.FromString,
          response_serializer=protos_dot_replay__buffer__pb2.StatsResponse.SerializeToString,
      ),
      'SaveGame': grpc.unary_unary_rpc_method_handler(
          servicer.SaveGame,
          request_deserializer=protos_dot_replay__buffer__pb2.GameHistory.FromString,
          response_serializer=protos_dot_replay__buffer__pb2.SaveGameResponse.SerializeToString,
      ),
      'SampleBatch': grpc.unary_unary_rpc_method_handler(
          servicer.SampleBatch,
          request_deserializer=protos_dot_replay__buffer__pb2.MiniBatchRequest.FromString,
          response_serializer=protos_dot_replay__buffer__pb2.MiniBatchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tensorflow.ReplayBuffer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
